spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:h2:mem:restaurantdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.restaurant.customer: debug